# Generated by Django 5.0.6 on 2024-06-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_de',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_fr',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
